import type { GermanChallenge } from './types';
import { assertDateKey } from './dateKey';

export const challenges: GermanChallenge[] = [
  {
    id: 'german-train-departure',
    phrase: 'Könnten Sie mir bitte sagen, wann der Zug abfährt?',
    meaning: 'Could you please tell me when the train leaves?',
    hint: 'Use an indirect question to ask politely for travel information.',
    question: 'What information does the speaker need?',
    options: ['The ticket price', 'The departure time', 'The platform number', 'The journey length'],
    correctOption: 1,
    explanation: '"Wann der Zug abfährt" asks when the train departs; the verb moves to the end of the indirect question.',
  },
  {
    id: 'german-cooking-despite-time',
    phrase: 'Obwohl ich wenig Zeit habe, koche ich heute selbst.',
    meaning: 'Although I have little time, I am cooking for myself today.',
    hint: '"Obwohl" introduces a contrast and sends the verb to the end of its clause.',
    question: 'Which two facts are being contrasted?',
    options: ['Having little time and cooking anyway', 'Being hungry and ordering food', 'Having guests and eating out', 'Shopping and saving money'],
    correctOption: 0,
    explanation: 'The speaker has little time but still chooses to cook, which creates the contrast introduced by "obwohl."',
  },
  {
    id: 'german-budget-habit',
    phrase: 'Seitdem ich ein Haushaltsbuch führe, spare ich jeden Monat mehr.',
    meaning: 'Since I started keeping a budget, I save more every month.',
    hint: 'A "Haushaltsbuch" records income and spending.',
    question: 'What habit helped the speaker save more?',
    options: ['Working longer hours', 'Using cash only', 'Keeping a budget', 'Canceling every subscription'],
    correctOption: 2,
    explanation: '"Ein Haushaltsbuch führen" means keeping a budget or household account book to track money.',
  },
  {
    id: 'german-share-tasks',
    phrase: 'Wenn wir die Aufgaben aufteilen, sind wir schneller fertig.',
    meaning: 'If we divide up the tasks, we will finish faster.',
    hint: '"Wenn" expresses a condition; "aufteilen" means to divide or share out.',
    question: 'What does the team plan to do?',
    options: ['Delay the deadline', 'Repeat every task', 'Work separately without a plan', 'Divide the work'],
    correctOption: 3,
    explanation: '"Die Aufgaben aufteilen" means dividing the work among the people involved.',
  },
  {
    id: 'german-professional-training',
    phrase: 'Ich interessiere mich für eine Weiterbildung im Projektmanagement.',
    meaning: 'I am interested in further training in project management.',
    hint: '"Sich interessieren für" always takes "für" plus the accusative.',
    question: 'What is the speaker considering?',
    options: ['A project-management course', 'A new apartment', 'A shorter commute', 'A team celebration'],
    correctOption: 0,
    explanation: '"Eine Weiterbildung" is further professional education or training.',
  },
  {
    id: 'german-health-advice',
    phrase: 'Der Arzt hat mir empfohlen, mich regelmäßig zu bewegen.',
    meaning: 'The doctor recommended that I exercise regularly.',
    hint: '"Jemandem etwas empfehlen" means recommending something to someone.',
    question: 'What advice did the doctor give?',
    options: ['Sleep less', 'Change doctors', 'Exercise regularly', 'Avoid all appointments'],
    correctOption: 2,
    explanation: '"Sich regelmäßig bewegen" means getting regular physical activity or exercise.',
  },
  {
    id: 'german-reschedule-meeting',
    phrase: 'Könnten wir den Termin auf Donnerstag verschieben?',
    meaning: 'Could we move the appointment to Thursday?',
    hint: 'The subjunctive form "könnten" makes a request more polite.',
    question: 'What change is being requested?',
    options: ['Canceling Thursday', 'Moving the appointment to Thursday', 'Making the meeting longer', 'Inviting another person'],
    correctOption: 1,
    explanation: '"Einen Termin verschieben" means rescheduling or moving an appointment.',
  },
  {
    id: 'german-compare-prices',
    phrase: 'Bevor ich etwas kaufe, vergleiche ich Preise und Bewertungen.',
    meaning: 'Before I buy something, I compare prices and reviews.',
    hint: '"Bevor" describes what happens before another action.',
    question: 'What happens before the purchase?',
    options: ['The item is returned', 'A loan is requested', 'The receipt is lost', 'Prices and reviews are compared'],
    correctOption: 3,
    explanation: 'The "bevor" clause establishes the purchase as later; comparing prices and reviews happens first.',
  },
  {
    id: 'german-home-office',
    phrase: 'Ich würde gern wissen, ob Homeoffice an zwei Tagen möglich ist.',
    meaning: 'I would like to know whether working from home is possible on two days.',
    hint: '"Ich würde gern wissen" is a polite way to introduce an indirect question.',
    question: 'What workplace option is the speaker asking about?',
    options: ['Two remote-work days', 'Two weeks of vacation', 'A different manager', 'A larger office'],
    correctOption: 0,
    explanation: '"Ob Homeoffice ... möglich ist" asks whether working remotely is possible; the verb is last in the indirect clause.',
  },
  {
    id: 'german-review-results',
    phrase: 'Wir sollten die Ergebnisse gemeinsam besprechen, bevor wir entscheiden.',
    meaning: 'We should discuss the results together before we decide.',
    hint: '"Sollten" expresses a recommendation rather than a strict command.',
    question: 'What should happen before a decision is made?',
    options: ['The results should be deleted', 'The meeting should end', 'The results should be discussed together', 'One person should decide alone'],
    correctOption: 2,
    explanation: 'The sentence recommends a shared discussion of the results before making the decision.',
  },
  {
    id: 'german-rain-commute',
    phrase: 'Wegen des starken Regens bin ich mit der Bahn zur Arbeit gefahren.',
    meaning: 'Because of the heavy rain, I took the train to work.',
    hint: '"Wegen" gives a reason; here it is followed by the genitive.',
    question: 'Why did the speaker take the train?',
    options: ['The car was sold', 'Because of heavy rain', 'To meet a friend', 'Because work started later'],
    correctOption: 1,
    explanation: '"Wegen des starken Regens" directly states heavy rain as the reason for the travel choice.',
  },
  {
    id: 'german-practice-confidence',
    phrase: 'Je öfter ich übe, desto sicherer spreche ich Deutsch.',
    meaning: 'The more often I practise, the more confidently I speak German.',
    hint: '"Je ..., desto ..." connects two changes that develop together.',
    question: 'What happens when the speaker practises more often?',
    options: ['German becomes less useful', 'The exercises become shorter', 'The speaker forgets more words', 'The speaker becomes more confident'],
    correctOption: 3,
    explanation: 'The paired comparison links more frequent practice with greater confidence when speaking.',
  },
  {
    id: 'german-email-follow-up',
    phrase: 'Nachdem ich die E-Mail gelesen hatte, rief ich meine Kollegin an.',
    meaning: 'After I had read the email, I called my colleague.',
    hint: '"Nachdem" makes the order of two past events clear.',
    question: 'Which action happened first?',
    options: ['Reading the email', 'Calling the colleague', 'Writing a new email', 'Leaving the office'],
    correctOption: 0,
    explanation: 'The past perfect "gelesen hatte" marks reading the email as earlier than the phone call.',
  },
  {
    id: 'german-celebrate-progress',
    phrase: 'Es lohnt sich, auch kleine Fortschritte bewusst zu feiern.',
    meaning: 'It is worthwhile to consciously celebrate even small improvements.',
    hint: '"Es lohnt sich" means that an action is worth the effort.',
    question: 'What does the sentence encourage?',
    options: ['Ignoring unfinished work', 'Celebrating small progress', 'Setting only large goals', 'Comparing yourself with others'],
    correctOption: 1,
    explanation: '"Kleine Fortschritte feiern" encourages noticing and celebrating incremental progress.',
  },
];

export function challengeForDate(date: string): GermanChallenge {
  assertDateKey(date);
  const day = Math.floor(Date.parse(`${date}T00:00:00Z`) / 86_400_000);
  return challenges[((day % challenges.length) + challenges.length) % challenges.length];
}
